; cnc-ddraw - https://github.com/FunkyFr3sh/cnc-ddraw

[ddraw]
width=800
height=600
fullscreen=false
windowed=true
maintas=false
boxing=false
maxfps=60
vsync=true
adjmouse=true
shader=Shaders\interpolation\catmull-rom-bilinear.glsl
posX=1097
posY=362
renderer=direct3d9
devmode=false
border=true
savesettings=1
resizable=true
d3d9_filter=2
anti_aliased_fonts_min_size=13
min_font_size=0
center_window=1
vhack=false
noactivateapp=true
maxgameticks=0
limiter_type=0
minfps=0
nonexclusive=true
singlecpu=false
resolutions=0
fixchilds=2
hook_peekmessage=false
hook=4

[LegendOfMagic]
nonexclusive=true
adjmouse=true

